# General aliases (short one-liners only)

alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias cd..="cd .."
alias cd2="cd ../../"
alias cd3="cd ../../../"
alias cd4="cd ../../../../"
alias cdocs="cd ~/Documents"
alias cdown="cd ~/Downloads"
alias chrome="google-chrome"
alias cnt="find . -type f | wc -l"
alias config="cd ~/workspace/config-files"
alias cprec="fc -ln -1 | awk '{\$1=\$1};1' | tee >(xclip -selection clipboard) >(xclip -selection primary)"
alias cpv="rsync -ah --info=progress2"
alias cronlog="grep CRON /var/log/syslog"
alias crypto="cd ~/workspace/crypto-noobs-v2/crypto-noobs-v2"
alias e="vim"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"
alias fhere="find . -name"
alias free="free -h"
alias grep="grep --color=auto"
alias hist="history"
alias histg="history | grep"
alias hour="cd ~/workspace/angular/angular-hour"
alias l="ls -CF"
alias la="ls -A"
alias lf="ls --human-readable --size -1 -S --classify"
alias line='wc -l $(find . -type f)'
alias ll="ls -alF"
alias ls="ls -altr --color"
alias lsl="ls -lrt | less"
alias metric="cd ~/workspace/metric5"
alias mkdir="mkdir -pv"
alias npmreset="rm -rf node_modules package-lock.json && npm install"
alias pbcopy="xclip -selection clipboard"
alias pbpaste="xclip -selection clipboard -o"
alias rmd="rm -drf"
alias roster="cd ~/workspace/roster-riddles"
alias sai="sudo apt install"
alias scripts="cd ~/workspace/scripts"
alias serv="systemctl list-units --type=service"
alias settings="gnome-control-center"
alias sl="ls"
alias slack="/snap/bin/slack"
alias spring='/home/nbrinson2/springsource/spring-tool-suite-4-4.21.0.RELEASE-e4.30.0-linux.gtk.x86_64/sts-4.21.0.RELEASE/SpringToolSuite4 &>/dev/null &'
alias src="source ~/.bashrc"
alias st="curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python3 -"
alias startplex="sudo service plexmediaserver start"
alias stash="cd ~/workspace/stash"
alias statplex="sudo systemctl status plexmediaserver"
alias stopplex="sudo service plexmediaserver stop"
alias top="top -o %MEM"
alias ttb="cd ~/workspace/ttb"
alias vib="nvim ~/.bashrc.d"
alias viba="nvim ~/.bashrc.d/10-aliases.sh"
alias vibcomp="nvim ~/.bashrc.d/90-completions.sh"
alias vibdock="nvim ~/.bashrc.d/40-docker.sh"
alias vibenv="nvim ~/.bashrc.d/00-env.sh"
alias vibfn="nvim ~/.bashrc.d/20-functions.sh"
alias vibgit="nvim ~/.bashrc.d/30-git.sh"
alias vibrc="nvim ~/.bashrc"
alias vibsec="nvim ~/.bash_secrets"
alias vibttb="nvim ~/.bashrc.d/50-ttb.sh"
alias watchers='echo "max_user_watches: $(cat /proc/sys/fs/inotify/max_user_watches)" && echo "max_user_instances: $(cat /proc/sys/fs/inotify/max_user_instances)" && echo "currently used: $(find /proc/*/fd -lname '\''anon_inode:inotify'\'' 2>/dev/null | wc -l)"'
alias work="cd ~/workspace"
alias wtr="curl wttr.in"
alias xo="xdg-open"
